export const ACTIONS = {
  ADD_MEAL: "ADD_MEAL",
  GET_MEALS_FROM_SERVER_DONE: "GET_MEALS_FROM_SERVER_DONE",
  REMOVE_MEAL: "REMOVE_MEAL",
  REMOVE_All_MEAL:"REMOVE_All_MEAL",
  CONFIG: {
    CHANGE_STARS_COLOR: "CHANGE_STARS_COLOR",
    CHANGE_IMAGE_SIZE: "CHANGE_IMAGE_SIZE",
  },
  COMMENT:{
    ADD_COMMENT:"ADD_COMMENT"
  }
};
